Diagnostics:
  ClangTidy:
    Add: ['*']
    Remove: [
      '*-braces-around-statements',
      '*-no-recursion',
      '*-signed-bitwise',
      '*DeprecatedOrUnsafeBufferHandling',
      '*avoid-goto',
      '*avoid-magic-numbers',
      '*c++98-compat',
      '*disabled-macro-expansion',
      '*else-after-return',
      '*gnu-statement-expression',
      '*gnu-zero-variadic-macro-arguments',
      '*init-variables',
      '*isolate-declaration',
      '*no-assembler',
      '*readability-magic-numbers',
      '*readability-identifier-length',
      '*todo*',
      'android*',
      'concurrency-mt-unsafe',
      'llvm-header-guard',
      'llvmlibc*',
      'altera-unroll-loops',
      'altera-struct-pack-align',
      'altera-id-dependent-backward-branch',
      '*fuchsia*',
      'modernize-use-trailing-return-type',
      'bugprone-easily-swappable-parameters',
      'bugprone-reserved-identifier',
      'cert-dcl37-c',
      'cert-dcl51-cpp',
      '*array-to-pointer-decay',
      '*avoid-c-arrays',
      '*bounds-constant-array-index',
      '*no-array-decay',
      '*owning-memory',
      '*pointer-arithmetic*',
      '*vararg',
      'cppcoreguidelines-pro-type-reinterpret-cast',
      'cppcoreguidelines-pro-type-const-cast',
      '*-non-private-member-variables-in-classes',
      'readability-implicit-bool-conversion',
      'google-default-arguments',
    ]

    # let g:ale_c_clangtidy_checks = [
    #             \   '*',
    #             \   '-*DeprecatedOrUnsafeBufferHandling',
    #             \   '-*bugprone-sizeof-expression',
    #             \   '-*macro-usage',
    #             \   '-*redundant-void-arg',
    #             \   '-*todo*',
    #             \   '-*uppercase-literal-suffix',
    #             \   '-cppcoreguidelines*',
    #             \ ]
