Diagnostics:
  ClangTidy:
    Add: ['*']
    Remove: [
      '*-braces-around-statements',
      '*-no-recursion',
      '*-non-private-member-variables-in-classes',
      '*-signed-bitwise',
      '*DeprecatedOrUnsafeBufferHandling',
      '*array-to-pointer-decay',
      '*avoid-c-arrays',
      '*avoid-goto',
      '*avoid-magic-numbers',
      '*bounds-constant-array-index',
      '*c++98-compat',
      '*disabled-macro-expansion',
      '*else-after-return',
      '*fuchsia*',
      '*gnu-statement-expression',
      '*gnu-zero-variadic-macro-arguments',
      '*init-variables',
      '*isolate-declaration',
      '*no-array-decay',
      '*no-assembler',
      '*owning-memory',
      '*pointer-arithmetic*',
      '*readability-identifier-length',
      '*readability-magic-numbers',
      '*todo*',
      '*vararg',
      'altera-id-dependent-backward-branch',
      'altera-struct-pack-align',
      'altera-unroll-loops',
      'android*',
      'bugprone-easily-swappable-parameters',
      'bugprone-reserved-identifier',
      'cert-dcl37-c',
      'cert-dcl51-cpp',
      'cert-err33-c',
      'concurrency-mt-unsafe',
      'cppcoreguidelines-avoid-non-const-global-variables',
      'cppcoreguidelines-pro-type-const-cast',
      'cppcoreguidelines-pro-type-reinterpret-cast',
      'google-default-arguments',
      'llvm-header-guard',
      'llvmlibc*',
      'modernize-use-trailing-return-type',
      'readability-implicit-bool-conversion',
      '*objc-*',
      'cppcoreguidelines-pro-type-union-access',
    ]


---

If:
  PathMatch: .*\.[ch]

Diagnostics:
  ClangTidy:
    Remove: [
      '*DeprecatedOrUnsafeBufferHandling',
      '*bugprone-sizeof-expression',
      '*macro-usage',
      '*redundant-void-arg',
      '*todo*',
      '*uppercase-literal-suffix',
      'cppcoreguidelines*',
      'hicpp*',
      'modernize*',
    ]
